In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('datasets/Disease and symptoms dataset.csv')
df.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.isnull().sum()

diseases                            0
anxiety and nervousness             0
depression                          0
shortness of breath                 0
depressive or psychotic symptoms    0
                                   ..
hip weakness                        0
back swelling                       0
ankle stiffness or tightness        0
ankle weakness                      0
neck weakness                       0
Length: 378, dtype: int64

In [5]:
encoder = LabelEncoder()

In [7]:
df.diseases = encoder.fit_transform(df.diseases)

In [8]:
df.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,531,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,531,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,531,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,531,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,531,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df.shape

(246945, 378)

In [10]:
df.columns

Index(['diseases', 'anxiety and nervousness', 'depression',
       'shortness of breath', 'depressive or psychotic symptoms',
       'sharp chest pain', 'dizziness', 'insomnia',
       'abnormal involuntary movements', 'chest tightness',
       ...
       'stuttering or stammering', 'problems with orgasm', 'nose deformity',
       'lump over jaw', 'sore in nose', 'hip weakness', 'back swelling',
       'ankle stiffness or tightness', 'ankle weakness', 'neck weakness'],
      dtype='str', length=378)

In [16]:
len(df.columns)

378

In [11]:
len(df.diseases.unique())

773

In [12]:
X = df.drop('diseases', axis=1)
y = df.diseases

In [17]:
X.shape

(246945, 377)

In [19]:
model = keras.Sequential([
    keras.Input(shape=(377,)),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.Dense(256, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(773, activation='softmax')
])

In [20]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [28]:
model.fit(X, y, epochs=40, batch_size=256)

Epoch 1/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.8901 - loss: 0.2582
Epoch 2/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.8913 - loss: 0.2568
Epoch 3/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.8910 - loss: 0.2586
Epoch 4/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.8923 - loss: 0.2525
Epoch 5/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.8923 - loss: 0.2522
Epoch 6/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.8924 - loss: 0.2515
Epoch 7/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.8930 - loss: 0.2506
Epoch 8/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.8926 - loss: 0.2514
Epoch 9/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.8938 - loss: 0.2483
Epoch 10/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8933 - loss: 0.2481
Epoch 11/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8940 - loss: 0.2473
Epoch 12/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8941 - loss: 0.2464
Epoch 13/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8946 - loss: 0.2450
Epoch 14/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8947 - loss: 0.2442
Epoch 15/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8947 - loss: 0.2460
Epoch 16/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8957 - loss: 0.2445
Epoch 17/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8958 - loss: 0.2407
Epoch 18/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8960 - loss: 0.2410
Epoch 19/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8962 - loss: 0.2410
Epoch 20/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8958 - loss: 0.2405
Epoch 21/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8963 - loss: 0.2403
Epoch 22/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8968 - loss: 0.2403
Epoch 23/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8971 - loss: 0.2381
Epoch 24/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8971 - loss: 0.2373
Epoch 25/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8974 - loss: 0.2378
Epoch 26/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8975 - loss: 0.2385
Epoch 27/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8970 - loss: 0.2382
Epoch 28/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8977 - loss: 0.2351
Epoch 29/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8977 - loss: 0.2349
Epoch 30/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8972 - loss: 0.2373
Epoch 31/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8980 - loss: 0.2340
Epoch 32/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8984 - loss: 0.2334
Epoch 33/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8982 - loss: 0.2345
Epoch 34/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8983 - loss: 0.2352
Epoch 35/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8988 - loss: 0.2336
Epoch 36/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8982 - loss: 0.2324
Epoch 37/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8986 - loss: 0.2313
Epoch 38/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8985 - loss: 0.2316
Epoch 39/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8985 - loss: 0.2322
Epoch 40/40
965/965 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8989 - loss: 0.2321

In [29]:
loss,accuracy = model.evaluate(X, y)
accuracy

7718/7718 ━━━━━━━━━━━━━━━━━━━━ 18s 2ms/step - accuracy: 0.9086 - loss: 0.2129

0.9085586071014404

In [30]:
model.save("model/disease_model.keras")

In [32]:
import pickle
pickle.dump(encoder, open("model/encoder.pkl", "wb"))

In [33]:
symptoms = X.columns.tolist()
pickle.dump(symptoms, open("model/symptoms.pkl", "wb"))